services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: 61c-server
    restart: unless-stopped
    env_file:
      - ./.env.production
    environment:
      NODE_ENV: production
      PORT: 5001
    ports:
      - "127.0.0.1:5001:5001"
    networks:
      - app_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    container_name: 61c-client
    restart: unless-stopped
    env_file:
      - ./.env.production
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    depends_on:
      - server
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
